name: .NET

on:
  push:
    tags:        
      - v**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.301
    - name: Set env
      run: |
        RELEASE_VERSION=$GITHUB_REF_NAME
        echo "RELEASE_VERSION=${RELEASE_VERSION:1}" >> $GITHUB_ENV
        echo $GITHUB_REF_NAME
        echo $RELEASE_VERSION
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release /p:Version=$RELEASE_VERSION --no-restore
    - name: Push
      run: |
        dotnet pack -c Release --no-build --verbosity normal /p:Version=$RELEASE_VERSION -o ./nugets
        cd ./nugets
        dotnet nuget push *.nupkg --skip-duplicate -s https://nuget.org -k ${{ secrets.API_KEY }} 
